exports.getActions = async function (req, res, next) {
  const actions = [
    {
      name: "Chronomètre",
      description: "Choisir un créneau pour éxécuter une réaction",
      img: "https://cdn-icons-png.flaticon.com/512/2928/2928750.png",
      to: "/app/action/timer",
      endpoint: "/area/actions/UniqueTimer",
      service: "Else",
    },
    {
      name: "Gmail Brouillon",
      description: "Déclencher une réaction si un nouveau brouillon est créé",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewDraft",
      endpoint: "/area/actions/TriggerWhenNewDraft",
      service: "Gmail",
    },
    {
      name: "Google Agenda Nouvel Calendrier",
      description: "Déclencher une réaction si un nouveau calendrier est créé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/1024px-Google_Calendar_icon_%282020%29.svg.png",
      to: "/app/action/googleNewCalendar",
      endpoint: "/area/actions/TriggerWhenNewCalendar",
      service: "Google Agenda",
    },
    {
      name: "Google Agenda Nouvel évènement",
      description: "Déclencher une réaction si un nouvel évènement est créé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/1024px-Google_Calendar_icon_%282020%29.svg.png",
      to: "/app/action/googleNewCalendarEvent",
      endpoint: "/area/actions/TriggerWhenNewCalendarEvent",
      service: "Google Agenda",
    },
    {
      name: "Gmail Nouveau Mail",
      description: "Déclencher une réaction si un nouveau mail est reçu",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewMail",
      endpoint: "/area/actions/TriggerWhenNewMail",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Label",
      description: "Déclencher une réaction si un nouveau label est créé",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewLabel",
      endpoint: "/area/actions/TriggerWhenNewLabel",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Mail Starred",
      description: "Déclencher une réaction si un nouveau mail est étoilé",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewStarredMail",
      endpoint: "/area/actions/TriggerWhenNewStarredMail",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Mail avec PJ",
      description:
        "Déclencher une réaction si un nouveau mail avec PJ est reçu",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewAttachment",
      endpoint: "/area/actions/TriggerWhenNewAttachment",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Mail avec recherche",
      description:
        "Déclencher une réaction si un nouveau mail avec recherche est reçu",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewEmailMatchingSearch",
      endpoint: "/area/actions/TriggerWhenNewEmailMatchingSearch",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Thread",
      description: "Déclencher une réaction si un nouveau thread est créé",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailNewThread",
      endpoint: "/area/actions/TriggerWhenNewThread",
      service: "Gmail",
    },
    {
      name: "Gmail Nouveau Contact",
      description: "Déclencher une réaction si un nouveau contact est créé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Google_Contacts_icon.svg/1200px-Google_Contacts_icon.svg.png",
      to: "/app/action/gmailNewContact",
      endpoint: "/area/actions/TriggerWhenNewContact",
      service: "Google Contacts",
    },
    {
      name: "Gmail Mail Supprimé",
      description: "Déclencher une réaction si un mail est supprimé",
      img: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
      to: "/app/action/gmailDeletedMail",
      endpoint: "/area/actions/TriggerWhenDeletedMail",
      service: "Gmail",
    },
    {
      name: "Google Agenda Évènement Annulé",
      description: "Déclencher une réaction si un évènement est annulé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/1024px-Google_Calendar_icon_%282020%29.svg.png",
      to: "/app/action/gmailEventCanceled",
      endpoint: "/area/actions/TriggerWhenEventCanceled",
      service: "Google Agenda",
    },
    {
      name: "Google Agenda Évènement Terminé",
      description: "Déclencher une réaction si un évènement est terminé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/1024px-Google_Calendar_icon_%282020%29.svg.png",
      to: "/app/action/gmailEventEnded",
      endpoint: "/area/actions/TriggerWhenEventEnded",
      service: "Google Agenda",
    },
    {
      name: "Google Agenda Évènement Commencé",
      description: "Déclencher une réaction si un évènement est commencé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/1024px-Google_Calendar_icon_%282020%29.svg.png",
      to: "/app/action/gmailEventStarted",
      endpoint: "/area/actions/TriggerWhenEventStarted",
      service: "Google Agenda",
    },
    {
      name: "Température",
      description: "Déclencher une réaction si la température est atteinte",
      img: "https://openweathermap.org/themes/openweathermap/assets/img/mobile_app/android-app-top-banner.png",
      to: "/app/action/temperatureReached",
      endpoint: "/area/actions/TriggerWhenTempReached",
      service: "OpenWeatherMap",
    },
    {
      name: "Chute de température",
      description: "Déclencher une réaction si la température chute",
      img: "https://openweathermap.org/themes/openweathermap/assets/img/mobile_app/android-app-top-banner.png",
      to: "/app/action/temperatureDropped",
      endpoint: "/area/actions/TriggerWhenTempDropped",
      service: "OpenWeatherMap",
    },
    {
      name: "Augmentation de température",
      description: "Déclencher une réaction si la température augmente",
      img: "https://openweathermap.org/themes/openweathermap/assets/img/mobile_app/android-app-top-banner.png",
      to: "/app/action/temperatureRise",
      endpoint: "/area/actions/TriggerWhenTempRise",
      service: "OpenWeatherMap",
    },
    {
      name: "Temps recherché",
      description: "Déclencher une réaction si le temps recherché est atteint",
      img: "https://openweathermap.org/themes/openweathermap/assets/img/mobile_app/android-app-top-banner.png",
      to: "/app/action/weatherReached",
      endpoint: "/area/actions/TriggerWhenWeatherReached",
      service: "OpenWeatherMap",
    },
    {
      name: "Contact Supprimé",
      description: "Déclencher une réaction si un contact est supprimé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Google_Contacts_icon.svg/1200px-Google_Contacts_icon.svg.png",
      to: "/app/action/googleContactDeleted",
      endpoint: "/area/actions/TriggerWhenContactDeleted",
      service: "Google Contacts",
    },
    {
      name: "Nouveau label Google Contacts",
      description: "Déclencher une réaction si un nouveau label est créé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Google_Contacts_icon.svg/1200px-Google_Contacts_icon.svg.png",
      to: "/app/action/googleContactLabel",
      endpoint: "/area/actions/TriggerWhenNewContactLabel",
      service: "Google Contacts",
    },
    {
      name: "Nom mis à jour Discord",
      description: "Déclencher une réaction si le nom Discord est mis à jour",
      img: "https://cdn-icons-png.flaticon.com/512/4945/4945973.png",
      to: "/app/action/discordNameUpdated",
      endpoint: "/area/actions/TriggerWhenDiscordNameUpdated",
      service: "Discord",
    },
    {
      name: "Nom mis à jour Facebook",
      description: "Déclencher une réaction si le nom Facebook est mis à jour",
      img: "https://www.unipile.com/wp-content/uploads/2022/06/logo-facebook.png",
      to: "/app/action/facebookNameUpdated",
      endpoint: "/area/actions/TriggerWhenFacebookNameUpdated",
      service: "Facebook",
    },
    {
      name: "Photo de profil mis à jour Facebook",
      description:
        "Déclencher une réaction si la photo de profil Facebook est mise à jour",
      img: "https://www.unipile.com/wp-content/uploads/2022/06/logo-facebook.png",
      to: "/app/action/facebookProfilePictureUpdated",
      endpoint: "/area/actions/TriggerWhenFacebookProfilePictureUpdated",
      service: "Facebook",
    },
    {
      name: "Nouveau Document",
      description: "Déclencher une réaction si un nouveau document est créé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Google_Docs_logo_%282014-2020%29.svg/1481px-Google_Docs_logo_%282014-2020%29.svg.png",
      to: "/app/action/googleNewDoc",
      endpoint: "/area/actions/TriggerWhenNewDoc",
      service: "Google Docs",
    },
    {
      name: "Document Supprimé",
      description: "Déclencher une réaction si un document est supprimé",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Google_Docs_logo_%282014-2020%29.svg/1481px-Google_Docs_logo_%282014-2020%29.svg.png",
      to: "/app/action/googleDocDeleted",
      endpoint: "/area/actions/TriggerWhenDocDeleted",
      service: "Google Docs",
    },
    {
      name: "Nouvelle Tâche",
      description: "Déclencher une réaction si une nouvelle tâche est créée",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Google_Docs_logo_%282014-2020%29.svg/1481px-Google_Docs_logo_%282014-2020%29.svg.png",
      to: "/app/action/googleNewTask",
      endpoint: "/area/actions/TriggerWhenNewTask",
      service: "Google Tasks",
    },
  ];
  res.status(200).json(actions);
};
